name: PummesPlugin
version: '1.0'
main: de.pummes.plugin.PummesPlugin
api-version: 1.17
authors: [ jetztmachtsbumm ]
description: Pummes
website: https://github.com/jetztmachtsbumm/PummesPlugin

commands:
  cords:
  arschbohrer: